# Generated by Django 3.0 on 2020-01-31 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Realtor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='realtors/%Y/%m/%d')),
                ('description', models.TextField(blank=True, max_length=200)),
                ('email', models.TextField(max_length=200, unique=True)),
                ('phone', models.IntegerField(max_length=12, unique=True)),
                ('is_mvp', models.BooleanField(default=False)),
                ('hire_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'realtor',
                'verbose_name_plural': 'realtors',
            },
        ),
    ]
