# Generated by Django 3.0 on 2020-02-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'contact', 'verbose_name_plural': 'contacts'},
        ),
        migrations.AddField(
            model_name='contacts',
            name='realtor_email',
            field=models.CharField(default='antonnifo@live.com', max_length=100),
            preserve_default=False,
        ),
    ]
