# Generated by Django 3.0 on 2020-01-31 12:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('garage', models.IntegerField(default=0)),
                ('sqft', models.IntegerField()),
                ('loot_size', models.DecimalField(decimal_places=1, max_digits=5)),
                ('photo_main', models.ImageField(upload_to='houses/%Y/%m/%d')),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='houses/%Y/%m/%d')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='houses/%Y/%m/%d')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='houses/%Y/%m/%d')),
                ('photo_4', models.ImageField(blank=True, null=True, upload_to='houses/%Y/%m/%d')),
                ('photo_5', models.ImageField(blank=True, null=True, upload_to='houses/%Y/%m/%d')),
                ('photo_6', models.ImageField(blank=True, null=True, upload_to='houses/%Y/%m/%d')),
                ('is_punlished', models.BooleanField(default=True)),
                ('list_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realtors.Realtor')),
            ],
            options={
                'verbose_name': 'listing',
                'verbose_name_plural': 'listings',
            },
        ),
    ]
